baseurl = "https://tuto-hugo.fr/"
title = "Tuto Hugo"
canonifyurls = true
paginate = 6
theme = "startbootstrap-clean-blog"
languageCode = "fr"
copyright = ""

[author]
    name = "Maxime Enrietto"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Un tutoriel adapté pour tout le monde."
  Author = "Maxime Enrietto"
  email = "contact@tuto-hugo.fr"
  Ganalytics = ""
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

[[params.social]]
    title = "twitter"
    url = ""
[[params.social]]
    title = "github"
    url = "https://github.com/e-maxime/site-tuto-hugo"
[[params.social]]
    title = "facebook"
    url = ""

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Les leçons"
  url = "/post/"
  weight = -180